import { JsonFragment } from '@ethersproject/abi'
import BalancerAbi from './balancer.json'
import ControllerABI from './Controller.json'
import ConvexRewardPoolABI from './ConvexRewardPool.json'
import CRVABI from './CRV.json'
import CurvePoolABI from './CurvePool.json'
import CVXABI from './CVX.json'
import ERC20Abi from './erc20.json'
import ERC677Abi from './erc677.json'
import FeeDistributorABI from './FeeDistributor.json'
import GaugeABI from './gauge.json'
import GaugeControllerABI from './GaugeController.json'
import ManagerABI from './Manager.json'
import MerkleDistributorABI from './MerkleDistributor.json'
import MinterABI from './minter.json'
import MinterWrapperABI from './MinterWrapper.json'
import MulticallABI from './Multicall.json'
import PickleChefABI from './pickleChef.json'
import PickleJarABI from './pickleJar.json'
import RewardsABI from './Rewards.json'
import StrategyABI from './Strategy.json'
import StableSwap3PoolConverterABI from './converter.json'
import SwapABI from './swap.json'
import UniswapRouterABI from './UniswapRouter.json'
import UNIV2PairAbi from './uni_v2_lp.json'
import VaultABI from './vault.json'
import VaultTokenABI from './VaultToken.json'
import VaultHelperABI from './vaultHelper.json'
import VotingEscrowABI from './votingEscrow.json'
import XYaxStakingABI from './xYax.json'
import YaxisChefABI from './yaxis_chef.json'
import YAxisMetaVaultABI from './yAxisMetaVault.json'

export const abis = {
	BalancerAbi: BalancerAbi as JsonFragment[],
	ControllerABI: ControllerABI as JsonFragment[],
	ConvexRewardPoolABI: ConvexRewardPoolABI as JsonFragment[],
	CRVABI: CRVABI as JsonFragment[],
	CurvePoolABI: CurvePoolABI as JsonFragment[],
	CVXABI: CVXABI as JsonFragment[],
	ERC20Abi: ERC20Abi as JsonFragment[],
	ERC677Abi: ERC677Abi as JsonFragment[],
	FeeDistributorABI: FeeDistributorABI as JsonFragment[],
	GaugeABI: GaugeABI as JsonFragment[],
	GaugeControllerABI: GaugeControllerABI as JsonFragment[],
	ManagerABI: ManagerABI as JsonFragment[],
	MerkleDistributorABI: MerkleDistributorABI as JsonFragment[],
	MinterABI: MinterABI as JsonFragment[],
	MinterWrapperABI: MinterWrapperABI as JsonFragment[],
	MulticallABI: MulticallABI as JsonFragment[],
	PickleChefABI: PickleChefABI as JsonFragment[],
	PickleJarABI: PickleJarABI as JsonFragment[],
	RewardsABI: RewardsABI as JsonFragment[],
	StrategyABI: StrategyABI as JsonFragment[],
	StableSwap3PoolConverterABI: StableSwap3PoolConverterABI as JsonFragment[],
	SwapABI: SwapABI as JsonFragment[],
	UniswapRouterABI: UniswapRouterABI as JsonFragment[],
	UNIV2PairAbi: UNIV2PairAbi as JsonFragment[],
	VaultABI: VaultABI as JsonFragment[],
	VaultTokenABI: VaultTokenABI as JsonFragment[],
	VaultHelperABI: VaultHelperABI as JsonFragment[],
	VotingEscrowABI: VotingEscrowABI as JsonFragment[],
	XYaxStakingABI: XYaxStakingABI as JsonFragment[],
	YaxisChefABI: YaxisChefABI as JsonFragment[],
	YAxisMetaVaultABI: YAxisMetaVaultABI as JsonFragment[],
}
